[versions]
kotlin = "2.2.0"
versions = "0.52.0"
shadow = "8.1.1"
logging = "7.0.7"
readingbat = "2.0.5"
utils = "2.3.11"
kotest = "6.0.0.M4"
ktor = "3.2.0"

[libraries]
readingbat-core = { group = "com.github.readingbat", name = "readingbat-core", version.ref = "readingbat" }
core-utils = { group = "com.github.pambrose.common-utils", name = "core-utils", version.ref = "utils" }
kotlin-logging = { group = "io.github.oshai", name = "kotlin-logging-jvm", version.ref = "logging" }

# Test dependencies
kotest-runner = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotest" }
kotest-assertions = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
ktor-server-test = { group = "io.ktor", name = "ktor-server-test-host", version.ref = "ktor" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
