[versions]
kotest = "6.0.0.M16"
kotlin = "2.2.10"
ktor = "3.2.3"
logging = "7.0.12"
readingbat = "2.1.1"
utils = "2.4.0"
versions = "0.52.0"

[libraries]
readingbat-core = { module = "com.github.readingbat.readingbat-core:readingbat-core", version.ref = "readingbat" }
readingbat-kotest = { module = "com.github.readingbat.readingbat-core:readingbat-kotest", version.ref = "readingbat" }
core-utils = { group = "com.github.pambrose.common-utils", name = "core-utils", version.ref = "utils" }
kotlin-logging = { group = "io.github.oshai", name = "kotlin-logging-jvm", version.ref = "logging" }

# Test dependencies
ktor-server-test = { group = "io.ktor", name = "ktor-server-test-host", version.ref = "ktor" }
kotest-assertions = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
kotest-runner = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotest" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }
ktor-plugin = { id = "io.ktor.plugin", version.ref = "ktor" }
